# Generated by Django 2.0.2 on 2018-06-02 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='profle_pic',
            new_name='profile_pic',
        ),
    ]
